startup: improve stop actions

diff --git a/hbase/resources/hbase-regionserver b/hbase/resources/hbase-regionserver
--- a/hbase/resources/hbase-regionserver
+++ b/hbase/resources/hbase-regionserver
@@ -70,20 +70,35 @@ function start {
 }
 
 function stop {
-  kill $(<$PID_FILE) 2>/dev/null
-  if [[ $? -eq 1 ]]; then
-    if [[ $KILL_FORCE -eq 1 ]]; then
-      sleep $KILL_SLEEP
-      kill -9 $(<$PID_FILE) 2>/dev/null
-      rm $PID_FILE
-      echo "$NAME stopped"
-    else
-      echo "$NAME already stopped"
-    fi
-  else
-    rm $PID_FILE
-    echo "$NAME stopped"
+  if [ ! -f $PID_FILE ]; then
+    echo "$NAME already stopped"
+    return
   fi
+  pid=$(<$PID_FILE)
+  kill $pid 2>/dev/null
+  i=0
+  while kill -0 $pid 2>dev/null && [ $i -lt $KILL_SLEEP ]; do
+    (( i++ ))
+    sleep 1
+  done
+  if ! kill -0 $pid 2>dev/null; then
+    rm $PID_FILE || true
+    echo "$NAME stopped"
+    return
+  fi
+  force_stop
+}
+
+function force_stop {
+  pid=$(<$PID_FILE)
+  kill -9 $pid 2>/dev/null
+  sleep 1
+  if kill -0 $pid; then
+    echo "$NAME failed to stop"
+    exit 1
+  fi
+  rm $PID_FILE
+  echo "$NAME forced stopped after ${KILL_SLEEP}s"
 }
 
 function status {
diff --git a/zookeeper/server/resources/zookeeper b/zookeeper/server/resources/zookeeper
--- a/zookeeper/server/resources/zookeeper
+++ b/zookeeper/server/resources/zookeeper
@@ -39,34 +39,54 @@ CMD="su - $USER -c \"export ZOOCFGDIR=$CONF_DIR; export ZOOCFG=zoo.cfg; source $
 function start {
   if [ -f $PID_FILE ]; then
     pid=`cat $PID_FILE`
-    echo $pid
     if kill -0 $pid >/dev/null 2>&1 $pid; then
-       echo "$NAME already started"
-       exit 3
+       echo "$NAME already running [$pid]"
+       exit 0
     else
       rm -rf $PID_FILE
     fi
   fi
   eval $CMD
-  #echo $! > $PID_FILE
-  echo "$NAME started [`cat $PID_FILE`]"
+  echo "$NAME running [`cat $PID_FILE`]"
 }
 
 function stop {
-  kill $(<$PID_FILE) 2>/dev/null
-  if [[ $? -eq 1 ]]; then
+  if [ ! -f $PID_FILE ]; then
     echo "$NAME already stopped"
-  else
-    rm $PID_FILE
-    echo "$NAME stopped"
+    return
   fi
+  pid=$(<$PID_FILE)
+  kill $pid 2>/dev/null
+  i=0
+  while kill -0 $pid 2>dev/null && [ $i -lt $KILL_SLEEP ]; do
+    (( i++ ))
+    sleep 1
+  done
+  if ! kill -0 $pid 2>dev/null; then
+    rm $PID_FILE || true
+    echo "$NAME stopped"
+    return
+  fi
+  force_stop
+}
+
+function force_stop {
+  pid=$(<$PID_FILE)
+  kill -9 $pid 2>/dev/null
+  sleep 1
+  if kill -0 $pid; then
+    echo "$NAME failed to stop"
+    exit 1
+  fi
+  rm $PID_FILE
+  echo "$NAME forced stopped after ${KILL_SLEEP}s"
 }
 
 function status {
   if [ -f $PID_FILE ]; then
     pid=`cat $PID_FILE`
     if kill -0 >/dev/null 2>&1 $pid; then
-       echo "$NAME started [$PID_FILE]"
+       echo "$NAME started [$pid]"
        exit 0
     fi
   fi
@@ -80,6 +100,7 @@ elif [[ $1 == "stop" ]]; then
   stop "$@"
 elif [[ $1 == "restart" ]]; then
   stop "$@"
+  sleep 1
   start "$@"
 elif [[ $1 == "status" ]]; then
   status "$@"
@@ -87,4 +108,3 @@ else
   N=/etc/init.d/$NAME
   echo "Usage: $N {start|stop|restart|status}" >&2
 fi
-
